# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('trade', models.CharField(blank=True, max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
