# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160219_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='obsevations',
            new_name='observations',
        ),
    ]
