# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160219_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(error_messages={'unique': 'Este código já está sendo usado por outro cliente, tente outro código'}, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('address', models.CharField(max_length=40, verbose_name='endereço')),
                ('number', models.CharField(max_length=10, verbose_name='número')),
                ('district', models.CharField(max_length=30, verbose_name='bairro')),
                ('city', models.CharField(max_length=30, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='estado')),
                ('zipcode', models.CharField(max_length=10, verbose_name='cep')),
                ('cpf', models.CharField(max_length=18, verbose_name='cpf')),
                ('rg', models.CharField(max_length=20, verbose_name='rg')),
                ('phone1', models.CharField(max_length=16, verbose_name='telefone1')),
                ('phone2', models.CharField(max_length=16, verbose_name='telefone2')),
                ('phone3', models.CharField(max_length=16, verbose_name='telefone3')),
                ('contact', models.CharField(max_length=30, verbose_name='contato')),
                ('email', models.EmailField(max_length=80, verbose_name='email')),
                ('complement', models.CharField(max_length=30, verbose_name='complemento')),
                ('observations', models.TextField(verbose_name='observações')),
            ],
            options={
                'verbose_name_plural': 'clientes',
                'verbose_name': 'cliente',
            },
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.IntegerField(error_messages={'unique': 'Esse código já está sendo usado por outro fornecedor, tente outro código'}, unique=True, verbose_name='código'),
        ),
    ]
