# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160413_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(error_messages={'unique': 'Esse código já está sendo usado por outro produto, tente outro código'}, max_length=15, unique=True, verbose_name='código')),
                ('description', models.CharField(max_length=50, verbose_name='descrição')),
                ('unity', models.CharField(blank=True, max_length=2, verbose_name='unidade')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, verbose_name='preço de custo')),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=7, verbose_name='margem de lucro')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, verbose_name='preço de venda')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=18, verbose_name='quantidade')),
                ('reference', models.CharField(blank=True, max_length=20, verbose_name='referência')),
                ('max_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=18, verbose_name='estoque máximo')),
                ('min_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=18, verbose_name='estoque mínimo')),
                ('bar_code', models.CharField(blank=True, max_length=14, verbose_name='codigo de barras')),
                ('ncm', models.CharField(blank=True, max_length=8, verbose_name='NCM')),
                ('observations', models.TextField(blank=True, verbose_name='observaçẽos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=40, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='complement',
            field=models.CharField(blank=True, max_length=30, verbose_name='complemento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=30, verbose_name='contato'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, max_length=18, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=30, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=80, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='observations',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.CharField(blank=True, max_length=16, verbose_name='telefone1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, max_length=16, verbose_name='telefone2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone3',
            field=models.CharField(blank=True, max_length=16, verbose_name='telefone3'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='rg'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='cep'),
        ),
    ]
