# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160426_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unity',
            field=models.CharField(blank=True, max_length=3, verbose_name='unidade'),
        ),
    ]
