# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160426_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='preço de custo'),
        ),
    ]
