# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160426_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='estoque máximo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='estoque mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='preço de venda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='margem de lucro'),
        ),
    ]
